ipc = true
splash = false

wallpaper {
    monitor = DP-2
    path = /home/nebo/Pictures/wallpapers_h
    order = random
    fit_mode = cover
    timeout = 3600
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/nebo/Pictures/wallpapers_v
    order = random
    fit_mode = cover
    timeout = 1800
}

wallpaper {
    monitor = DP-1
    path = /home/nebo/Pictures/wallpapers_h
    order = random
    fit_mode = cover
    timeout = 1800
}
