# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale
# Portrait/rotated secondary monitor (transform: 1 = 90°, 3 = 270°)


# Left Monitor (Acer KG241 P)
monitor = HDMI-A-1, 1920x1080@119.98200, 0x0, 1, transform, 1

# Center/Main Monitor (Acer VG270 P)
monitor = DP-2, 1920x1080@143.85500, 1080x0, 1

# Right Monitor (Dell P1913)
monitor = DP-1, 1440x900@59.88700, 3000x0, 1
