# █ █ █▄█ █▀█ █▀█ █   █▀█ █▀▀ █▄▀
# █▀█  █  █▀▀ █▀▄ █▄▄ █▄█ █▄▄ █ █


## General configs
general {
    ignore_empty_input = true
    hide_cursor = true
}

 auth {
     fingerprint {
         enabled = true
         ready_message = Scan fingerprint to unlock
         present_message = Scanning...
         retry_delay = 250 # in milliseconds
     }
 }


animations {
    enabled = false
}

## Wallpaper
background {
    monitor =
    path = screenshot
    blur_passes = 3
}



# INPUT FIELD
input-field {
    monitor =
    size = 650, 100
    position = 0,0
    rounding = 0
    halign = center
    valign = center

    outline_thickness = 4
    dots_size = 0.3 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgba(86, 90, 90, 1)
    inner_color = rgba(40, 40, 40, 1)
    font_color = rgb(200, 200, 200)
    fade_on_empty = false

    font_family = JetBrainsMono Nerd Font

    placeholder_text = Enter Password

}
